#!/bin/bash

echo "Setting up Router"
ifconfig r1-eth0 0
ifconfig r1-eth1 0
ifconfig r1-eth0 hw ether 00:00:00:00:01:01
ifconfig r1-eth1 hw ether 00:00:00:00:01:02
ip addr add 10.0.1.1/24 brd + dev r1-eth0
ip addr add 10.0.2.1/24 brd + dev r1-eth1
echo 1 > /proc/sys/net/ipv4/ip_forward

